<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configurations>Developer - Debug;Release - Alpha;Release - Beta;Release - Final</Configurations>
    <Platforms>x64</Platforms>
    <TargetFrameworks>net48</TargetFrameworks>
    <AssemblyName>DatapathFix</AssemblyName>
    <RootNamespace>DatapathFix</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Developer - Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Developer\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Alpha|x64'">
    <OutputPath>bin\Release\Alpha\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Beta|x64'">
    <OutputPath>bin\Release\Beta\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Final|x64'">
    <OutputPath>bin\Release\Final\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command='if not exist "$(SolutionDir)$(OutDir)Plugins\DatapathFix\" mkdir "$(SolutionDir)$(OutDir)Plugins\DatapathFix\"' />
    <Exec Command='if not exist "$(SolutionDir)..\FrostyModManager\$(OutDir)Plugins\DatapathFix\" mkdir "$(SolutionDir)..\FrostyModManager\$(OutDir)Plugins\DatapathFix\"' />
    <Exec Command='xcopy /Y "$(TargetPath)" "$(SolutionDir)$(OutDir)Plugins\DatapathFix\"' />
    <Exec Command='xcopy /Y "$(TargetPath)" "$(SolutionDir)..\FrostyModManager\$(OutDir)Plugins\DatapathFix\"' />
  </Target>

</Project>
